# Generated by Django 4.1.2 on 2022-10-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='userID',
            new_name='user',
        ),
    ]
