# Generated by Django 4.1.2 on 2022-10-31 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_userid_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='counsellorID',
            field=models.ForeignKey(db_column='counsellorID', on_delete=django.db.models.deletion.CASCADE, to='appointment.counsellor'),
        ),
    ]
