# Generated by Django 4.1.2 on 2022-10-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_counsellorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00', 'Nine Am'), ('10:00', 'Ten Am'), ('11:00', 'Eleven Am'), ('12:00', 'Twelve Pm'), ('14:00', 'Two Pm'), ('15:00', 'Three Pm'), ('16:00', 'Four Pm'), ('17:00', 'Five Pm')], default='10:00', max_length=100),
        ),
    ]
