# Generated by Django 4.1.2 on 2022-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='postal_code',
            field=models.CharField(default=637634, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='images',
            field=models.CharField(max_length=300),
        ),
    ]
