# Generated by Django 4.1.2 on 2022-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_counsellor_lat_counsellor_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00', 'Nine Am'), ('10:00', 'Ten Am'), ('11:00', 'Eleven Am'), ('12:00', 'Twelve Pm'), ('14:00', 'Two Pm'), ('15:00', 'Three Pm'), ('16:00', 'Four Pm'), ('17:00', 'Five Pm'), ('18:00', 'Six Pm'), ('19:00', 'Seven Pm')], default='10:00', max_length=100),
        ),
    ]
