# Generated by Django 4.1 on 2022-10-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                db_column="pid",
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.post",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                db_column="pid",
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.post",
            ),
        ),
    ]
